services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      # Explicitly set Linux paths for the GIS libraries
      - DB_HOST=host.docker.internal
      - GDAL_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libgdal.so
      - GEOS_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libgeos_c.so
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - USE_S3=True
