# Generated by Django 6.0 on 2025-12-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='stall_type',
            field=models.CharField(choices=[('PWD', 'PWD'), ('F', 'Female'), ('U', 'Unisex'), ('M', 'Male')], default='U', max_length=50),
        ),
    ]
