# Generated by Django 6.0 on 2025-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_stall_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='stall_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('PWD', 'PWD'), ('U', 'Unisex')], default='U', max_length=50),
        ),
    ]
