# Generated by Django 6.0 on 2026-01-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_stall_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='stall_type',
            field=models.CharField(choices=[('PWD', 'PWD'), ('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], default='U', max_length=50),
        ),
    ]
