# Generated by Django 6.0 on 2026-03-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_stall_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='stall_type',
            field=models.CharField(choices=[('U', 'Unisex'), ('M', 'Male'), ('F', 'Female'), ('PWD', 'PWD')], default='U', max_length=50),
        ),
    ]
