# Generated by Django 6.0 on 2026-04-02 07:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_stall_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='stall_type',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex'), ('PWD', 'PWD')], default='U', max_length=50),
        ),
    ]
