# Generated by Django 6.0 on 2026-04-02 07:46

from django.db import migrations
from django.contrib.gis.geos import Point

def migrate_lat_long_to_point(apps, schema_editor):
    Locations = apps.get_model('locations', 'Location')
    for location in Locations.objects.all():
        if location.longitude and location.longitude:
            location.point = Point((location.longitude, location.latitude))
            location.save()

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_point_alter_location_stall_type'),
    ]

    operations = [
        migrations.RunPython(migrate_lat_long_to_point)
    ]
