# Generated by Django 6.0 on 2026-04-02 07:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20260402_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='stall_type',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('PWD', 'PWD'), ('U', 'Unisex')], default='U', max_length=50),
        ),
    ]
