# Generated by Django 6.0 on 2026-04-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_location_point_alter_location_stall_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='location',
            name='stall_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('PWD', 'Pwd'), ('U', 'Unisex')], default='U', max_length=50),
        ),
    ]
