# Generated by Django 6.0 on 2026-05-19 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_remove_location_latitude_remove_location_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('For Review', 'Pending'), ('Rejected', 'Rejected')], default='For Review', max_length=30),
        ),
    ]
